#!/usr/bin/env python3
"""
This module defines the async_comprehension coroutine.
It demonstrates the use of asynchronous comprehensions to collect data.
"""

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Use asynchronous comprehension to gather 10 random numbers generated by async_generator.

    Returns:
        A list containing 10 random floating-point numbers obtained asynchronously.
    """
    return [number async for number in async_generator()]
